### PR TITLE
Allow passing a custom timezone to delorean.now().

### PR DESCRIPTION
**Pull request by nlsdfnbch**

### CODE REVIEW

**Comment by myusuf3** [comment]
Mind updating associated documentation?

**Comment by nlsdfnbch** [comment]
Not at all!

**Comment by myusuf3** [comment]
If you could!

**Comment by myusuf3** [comment]
I want to merge this in, has it been tested as well?

**Comment by nlsdfnbch** [comment]
@myusuf3 - I relied on your tests to check it; However, a manual check using the cli worked for me.

**Pull request merged**
